### ISSUE TITLE
BUG - generate_manifest.py throws error when PYTHON/MANIFEST folder doesn't exist

### ISSUE THREAD

**Issue by dev-nested** [flojoy-io/studio#271]
# Description

When the cmd `python3 generate_manifest.py`,is run, it fails if it can't find the `PYTHON/MANIFEST` folder. This can happen after freshly cloning a repo.

Error log:
```
"all_files = [f for f in listdir(full_path) if (isfile(join(full_path, f)))]
FileNotFoundError: [Errno 2] No such file or directory: 'PYTHON/MANIFEST' " 
```

# Expected Behavior
The `generate_manifest.py` script should create the subfolders as needed.

**Comment by jackparmer** [comment]
is this still the case @smahmed776 ? let's close please if not

**Comment by smahmed776** [comment]
@jackparmer This can happen only if the repository is cloned without `--recursive` argument and run the bash script with `-s` argument to skip the submodules update (submodule update is bypassed in both cloning repo and running startup script). Otherwise startup script should create and update these folders with `git submodule update --init --recursive` command before running `python3 generate_manifest.py`.

 So do we still need to fix this to create these subfolders?
