### ISSUE TITLE
open & run every example app in the `apps` repo. validate that run results display in the CTRL panel

### ISSUE THREAD

**Issue by jalium** [flojoy-io/studio#317]
To Do: 
open & run every example app in the app’s repo. validate that run results display in the CTRL panel

- need more automation
- may need to add mocking, if so - convert to new tasks

**Comment by jackparmer** [comment]
I think that this e2e test is supposed to do this: 
https://github.com/flojoy-io/studio/blob/develop/cypress/e2e/example_apps.spec.cy.ts

It could use some enhancements, though:
- [ ] verify that it's working and running in CI 😆 
- [ ] instead of using https://github.com/flojoy-io/studio/blob/develop/cypress/e2e/config_example_app_test.json to decide which apps to run, we should simply run all apps in the `apps` repo. there shouldn't be anymore sample apps within `studio` - they should all be in `apps` now
- [ ] in addition to running the app and verifying a successful run, should validate the control panel state for apps that have a control panel. changing a widget and rerunning the app should result in a different output. 
- [ ] would be nice to add Percy to CI for image screenshots of the 3 tabs after runs (App, Debug, and CTRL)
