### ISSUE TITLE
Get rid of @cypress/snapshot since it is no longer supported

### ISSUE THREAD

**Issue by itsjoeoui** [flojoy-io/studio#356]
Snapshot testing, while useful for catching regressions, can often lead to brittle tests that break unnecessarily when small changes are made to the code being tested. This is especially true for UI testing, where even minor changes in styling or layout can cause snapshots to fail.

In addition, Cypress already provides powerful visual testing capabilities that go beyond snapshot testing. For example, the cy.screenshot() command can be used to take screenshots of elements or the entire page during a test, which can be used for visual regression testing.

**Comment by jackparmer** [comment]
> ...cy.screenshot() command can be used to take screenshots of elements or the entire page during a test, which can be used for visual regression testing.

with testing in general, let's buy over build as much as possible, because our team is small and we can't afford to maintain much home-built infrastructyre ourselves

we used this visual testing framework with plotly:
https://percy.io/

looks like refect has one now, too. i haven't compared
https://reflect.run/visual-testing/
